######################################################################
#
# File name : ANNfull_TB_wave.do
# Created on: Wed Sep 03 19:00:21 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
