######################################################################
#
# File name : ANNfull_TB_simulate.do
# Created on: Sun Sep 07 03:34:55 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.ANNfull_TB xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {ANNfull_TB_wave.do}

view wave
view structure
view signals

do {ANNfull_TB.udo}

run 1000ns
