######################################################################
#
# File name : convLayerSingle_TB_simulate.do
# Created on: Sun Sep 07 01:37:36 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.convLayerSingle_TB xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {convLayerSingle_TB_wave.do}

view wave
view structure
view signals

do {convLayerSingle_TB.udo}

run 1000ns
