######################################################################
#
# File name : convLayerMulti_TB_wave.do
# Created on: Wed Sep 03 12:22:50 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
