######################################################################
#
# File name : convUnit_TB_wave.do
# Created on: Wed Sep 03 15:28:16 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
