######################################################################
#
# File name : FindMax_TB_simulate.do
# Created on: Wed Sep 03 22:03:57 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.FindMax_TB xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {FindMax_TB_wave.do}

view wave
view structure
view signals

do {FindMax_TB.udo}

run 1000ns
