######################################################################
#
# File name : FindMax_TB_compile.do
# Created on: Wed Sep 03 22:03:56 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog -64 -incr -work xil_defaultlib  \
"../../../sources_1/imports/FindMax.v" \
"../../../sources_1/TB/FindMax_TB.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

