######################################################################
#
# File name : floatAdd16_TB_compile.do
# Created on: Wed Sep 03 14:36:20 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog -64 -incr -work xil_defaultlib  \
"../../../sources_1/imports/floatAdd16.v" \
"../../../sources_1/TB/floatAdd16_TB.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

