######################################################################
#
# File name : fp16_max_TB_compile.do
# Created on: Mon Sep 08 13:54:23 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog -64 -incr -work xil_defaultlib  \
"../../../sources_1/imports/max.v" \
"../../../sources_1/TB/max_TB.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

