######################################################################
#
# File name : fp16_max_TB_wave.do
# Created on: Mon Sep 08 13:53:58 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
