######################################################################
#
# File name : fp16_max_TB_simulate.do
# Created on: Mon Sep 08 13:54:25 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.fp16_max_TB xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {fp16_max_TB_wave.do}

view wave
view structure
view signals

do {fp16_max_TB.udo}

run 1000ns
