######################################################################
#
# File name : integrationConv_TB_compile.do
# Created on: Mon Sep 08 14:37:57 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog -64 -incr -work xil_defaultlib  \
"../../../sources_1/new/IntegrationConvPart.v" \
"../../../sources_1/imports/MaxPoolMulti.v" \
"../../../sources_1/imports/MaxPoolSingle.v" \
"../../../sources_1/imports/RFselector.v" \
"../../../sources_1/imports/UsingTheRelu16.v" \
"../../../sources_1/new/convLayerMulti.v" \
"../../../sources_1/imports/convLayerSingle.v" \
"../../../sources_1/imports/convUnit.v" \
"../../../sources_1/imports/floatAdd16.v" \
"../../../sources_1/imports/floatMult16.v" \
"../../../sources_1/imports/max.v" \
"../../../sources_1/new/padding.v" \
"../../../sources_1/imports/processingElement16.v" \
"../../../sources_1/TB/IntegrationConvPart_TB.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

