######################################################################
#
# File name : IntegrationConvPart_TB_compile.do
# Created on: Fri Sep 05 17:05:38 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog -64 -incr -work xil_defaultlib  \
"../../../sources_1/TB/IntegrationConvPart_TB.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

