######################################################################
#
# File name : IntegrationConvPart_TB_wave.do
# Created on: Fri Sep 05 17:05:44 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
