######################################################################
#
# File name : IntegrationConvPart_TB_simulate.do
# Created on: Fri Sep 05 17:05:44 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.IntegrationConvPart_TB xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {IntegrationConvPart_TB_wave.do}

view wave
view structure
view signals

do {IntegrationConvPart_TB.udo}

run 1000ns
