######################################################################
#
# File name : integrationConv_TB_wave.do
# Created on: Mon Sep 08 12:01:53 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
