######################################################################
#
# File name : Lenet_TB_simulate.do
# Created on: Mon Sep 08 16:00:33 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.Lenet_TB xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {Lenet_TB_wave.do}

view wave
view structure
view signals

do {Lenet_TB.udo}

run 1000ns
