######################################################################
#
# File name : Lenet_TB_wave.do
# Created on: Sat Sep 06 11:22:53 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
