######################################################################
#
# File name : padding_TB_simulate.do
# Created on: Tue Sep 02 22:27:39 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.padding_TB xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {padding_TB_wave.do}

view wave
view structure
view signals

do {padding_TB.udo}

run 1000ns
