######################################################################
#
# File name : padding_TB_wave.do
# Created on: Tue Sep 02 21:03:42 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
