######################################################################
#
# File name : processingElement16_TB_simulate.do
# Created on: Wed Sep 03 14:03:00 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.processingElement16_TB xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {processingElement16_TB_wave.do}

view wave
view structure
view signals

do {processingElement16_TB.udo}

run 1000ns
