######################################################################
#
# File name : processingElement16_TB_wave.do
# Created on: Wed Sep 03 14:03:00 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
