######################################################################
#
# File name : padding_TB_compile.do
# Created on: Tue Sep 02 21:03:40 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\modeltech64_2019.2\\win64\\vlib modelsim_lib/work
D:\\modeltech64_2019.2\\win64\\vlib modelsim_lib/msim

D:\\modeltech64_2019.2\\win64\\vlib modelsim_lib/msim/xil_defaultlib

D:\\modeltech64_2019.2\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

D:\\modeltech64_2019.2\\win64\\vlog -64 -incr -work xil_defaultlib  \
"../../../sources_1/new/ANNfull.v" \
"../../../sources_1/imports/Integration first part/FindMax.v" \
"../../../sources_1/imports/Integration first part/IEEE162IEEE32.v" \
"../../../sources_1/new/IntegrationConvPart.v" \
"../../../sources_1/new/Lenet.v" \
"../../../sources_1/imports/Integration first part/MaxPoolMulti.v" \
"../../../sources_1/imports/Integration first part/MaxPoolSingle.v" \
"../../../sources_1/imports/Integration first part/RFselector.v" \
"../../../sources_1/imports/Integration first part/UsingTheRelu.v" \
"../../../sources_1/imports/Integration first part/UsingTheRelu16.v" \
"../../../sources_1/imports/Integration first part/activationFunction.v" \
"../../../sources_1/new/convLayerMulti.v" \
"../../../sources_1/imports/Integration first part/convLayerSingle.v" \
"../../../sources_1/imports/Integration first part/convUnit.v" \
"../../../sources_1/imports/Integration first part/floatAdd.v" \
"../../../sources_1/imports/Integration first part/floatAdd16.v" \
"../../../sources_1/imports/Integration first part/floatMult.v" \
"../../../sources_1/imports/Integration first part/floatMult16.v" \
"../../../sources_1/imports/Integration first part/layer.v" \
"../../../sources_1/imports/Integration first part/TB/lenet_TB.v" \
"../../../sources_1/imports/Integration first part/max.v" \
"../../../sources_1/new/padding.v" \
"../../../sources_1/imports/Integration first part/processingElement.v" \
"../../../sources_1/imports/Integration first part/processingElement16.v" \
"../../../sources_1/imports/Integration first part/TB/softmax_TB.v" \
"../../../sources_1/imports/Integration first part/weightMemory.v" \


# compile glbl module
D:\\modeltech64_2019.2\\win64\\vlog -work xil_defaultlib "glbl.v"

######################################################################
#
# File name : padding_TB_simulate.do
# Created on: Tue Sep 02 21:03:42 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.padding_TB xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1
######################################################################
# user config 
# Created date: 2025/9/2 21:3:42
######################################################################
#log 全部波形数据
log -r /*       
#设置数值显示的方式  eage: radix [-binary | -octal | -decimal | -unsigned | -ascii | time] | -showbase | -symbolic]
radix hex 
#打开wave窗口
view wave
#显示结构
view structure
#显示信号
view signals
# 运行保存的波形文件
do wave.do
#运行时间
run 10ms
