######################################################################
#
# File name : UsingTheRelu16_TB_wave.do
# Created on: Wed Sep 03 11:31:15 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
